{% set name = "snakescale" %}
{% set version = "0.3.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  #url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  #sha256: cf7775431ab352a3f2bf957ca0ab4ea93560ba0e1fa1dddeccf4269d077dfca1

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
    - snakemake >=4.5.1
  run:
    - python
    - snakemake >=4.5.1

about:
  home: https://github.com/clintval/snakescale
  license: MIT
  license_family: MIT
  license_file: 
  summary: Non-strict wrappers for the data pipelining language Snakemake.
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - clintval
